name: Release Docker Image

on:
  push:
    branches:
      - main

jobs:
  release-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image from Docker Hub
        run: docker pull szymonstanek/restfulmap:latest

      - name: Tag Docker Image
        run: docker tag szymonstanek/restfulmap:latest ghcr.io/${{ github.repository_owner }}/restfulmap:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/restfulmap:latest

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.run_id }}
          name: Release ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
